/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DemoDocGhiDoiTuong;

import Buoi6_FileReader_FileWriter.s5_DocVaGhiDoiTuong;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LegendNguyen
 */
public class Main extends javax.swing.JFrame {

    List<Teacher> lstTeacher = new ArrayList<>();
    DefaultTableModel defaultTableModel;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    //Viết 1 hàm fake data

    void fakeData() {
        Teacher tc1 = new Teacher("dungna", "Dũng");
        Teacher tc2 = new Teacher("dungna1", "Dũng1");
        Teacher tc3 = new Teacher("dungna2", "Dũng2");
        Teacher tc4 = new Teacher("dungna3", "Dũng3");
        lstTeacher.add(tc1);
        lstTeacher.add(tc2);
        lstTeacher.add(tc3);
        lstTeacher.add(tc4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_docFile = new javax.swing.JButton();
        btn_Them = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_gv = new javax.swing.JTable();
        btn_ghiFile = new javax.swing.JButton();
        btn_Fakedata = new javax.swing.JButton();
        txt_MaGV = new javax.swing.JTextField();
        txt_TenGV = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_docFile.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_docFile.setText("Đọc file");
        btn_docFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_docFileActionPerformed(evt);
            }
        });

        btn_Them.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_Them.setText("Thêm");

        tbl_gv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_gv);

        btn_ghiFile.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_ghiFile.setText("Ghi file");
        btn_ghiFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ghiFileActionPerformed(evt);
            }
        });

        btn_Fakedata.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_Fakedata.setText("Fake data");
        btn_Fakedata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FakedataActionPerformed(evt);
            }
        });

        txt_MaGV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_MaGV.setText("Mã GV");

        txt_TenGV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_TenGV.setText("Tên GV");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_ghiFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_docFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Fakedata, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_MaGV)
                            .addComponent(txt_TenGV, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Them)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Fakedata)
                        .addGap(27, 27, 27)
                        .addComponent(btn_docFile)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ghiFile))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_MaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txt_TenGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_FakedataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FakedataActionPerformed
        fakeData();
        defaultTableModel = (DefaultTableModel) tbl_gv.getModel();
        defaultTableModel.addColumn("MaGV");
        defaultTableModel.addColumn("TenGV");
        defaultTableModel.setRowCount(0);
        for (Teacher x : lstTeacher) {
            defaultTableModel.addRow(new Object[]{x.getMaGV(), x.getTenGV()});
        }

    }//GEN-LAST:event_btn_FakedataActionPerformed

    private void btn_ghiFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ghiFileActionPerformed
        try {
            File file = new File("teacherTest.txt");
            if (!file.exists()) {
                try {
                    file.createNewFile();
                } catch (IOException ex) {
                    Logger.getLogger(s5_DocVaGhiDoiTuong.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            FileOutputStream fos = new FileOutputStream(file);
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            for (var teacher : lstTeacher) {
                oos.writeObject(teacher);
            }
            oos.close();
            fos.close();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_ghiFileActionPerformed

    private void btn_docFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_docFileActionPerformed
        try {
            File file = new File("teacherTest.txt");
            if (!file.exists()) {
                try {
                    file.createNewFile();
                } catch (IOException ex) {
                    Logger.getLogger(s5_DocVaGhiDoiTuong.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            FileInputStream fis = new FileInputStream(file);
            ObjectInputStream ois = new ObjectInputStream(fis);

            Teacher teacherIn = new Teacher();

            while (fis.available() > 0) {
                teacherIn = (Teacher) ois.readObject();
                lstTeacher.add(teacherIn);

            }

            defaultTableModel = (DefaultTableModel) tbl_gv.getModel();
            defaultTableModel.addColumn("MaGV");
            defaultTableModel.addColumn("TenGV");
            defaultTableModel.setRowCount(0);
            for (Teacher x : lstTeacher) {
                defaultTableModel.addRow(new Object[]{x.getMaGV(), x.getTenGV()});
            }

            ois.close();
            fis.close();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_docFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Fakedata;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_docFile;
    private javax.swing.JButton btn_ghiFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_gv;
    private javax.swing.JTextField txt_MaGV;
    private javax.swing.JTextField txt_TenGV;
    // End of variables declaration//GEN-END:variables
}
