/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Buoi2_JAVA_Swing;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LegendNguyen
 */
public class S11_JFrameTable extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTable
     */
    public S11_JFrameTable() {
        initComponents();
        tableGiaoVien();
    }
    
    Vector vtcData;
    void tableGiaoVien() {
        //Tạo tên cột
        Vector vtcHeader = new Vector();
        vtcHeader.add("Mã Giáo Viên");
        vtcHeader.add("Tên Giáo Viên");
        vtcHeader.add("Số Điện Thoại");        
        
        vtcData = new Vector();
        Vector vtcRow1 = new Vector();
        vtcRow1.add("dungna29");
        vtcRow1.add("Nguyễn Anh Dũng");
        vtcRow1.add("0869858");
        vtcData.add(vtcRow1);
        Vector vtcRow2 = new Vector();
        vtcRow2.add("hoangnh15");
        vtcRow2.add("Nguyễn Hoàng Anh");
        vtcRow2.add("0123456789");
        vtcData.add(vtcRow2);
        table_GiaoVien.setModel(new DefaultTableModel(vtcData, vtcHeader));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_GiaoVien = new javax.swing.JTable();
        txt_TenGiaoVien = new javax.swing.JTextField();
        txt_MaGv = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_GiaoVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        table_GiaoVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_GiaoVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_GiaoVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_GiaoVien);

        txt_TenGiaoVien.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txt_TenGiaoVien.setText("TenGV");

        txt_MaGv.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txt_MaGv.setText("MaGV");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_MaGv)
                    .addComponent(txt_TenGiaoVien, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txt_MaGv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_TenGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_GiaoVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_GiaoVienMouseClicked
        int temp = table_GiaoVien.getSelectedRow();
        Vector vector = (Vector) vtcData.get(temp);
        String id = (String) vector.get(0);
        String ten = (String) vector.get(1);
        txt_MaGv.setText(id);
        txt_TenGiaoVien.setText(ten);
    }//GEN-LAST:event_table_GiaoVienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S11_JFrameTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S11_JFrameTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S11_JFrameTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S11_JFrameTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S11_JFrameTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_GiaoVien;
    private javax.swing.JTextField txt_MaGv;
    private javax.swing.JTextField txt_TenGiaoVien;
    // End of variables declaration//GEN-END:variables
}
