/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Buoi2_JAVA_Swing;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author LegendNguyen
 */
public class S9_JFrameCombobox extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCombobox
     */
    String[] data = {
        "Việt Nam", "United States", "Singapore", "Malaysia"
    };
   

    public S9_JFrameCombobox() {
        initComponents();
        //Contructor 
        // Mảng dữ liệu kiểu chuỗi String

        //Đổ dữ liệu vào trong cbc thông qua hàm setModel
        cbc_quocgia.setModel(new DefaultComboBoxModel(data));
        //Gán vị trí số 2 là vị trí hiển thị theo index
        cbc_quocgia.setSelectedIndex(2);
        
//      String[] dataNamSinh = new String[2021 - 1900];
        String[] dataNamSinh = new String[Integer.parseInt(txt_NamketThuc.getText()) - Integer.parseInt(txt_NamBatDau.getText())];
        //Dùng vòng lặp để tạo năm sinh tự động
        for (int i = 0; i < dataNamSinh.length; i++) {
            dataNamSinh[i] = String.valueOf(Integer.parseInt(txt_NamBatDau.getText()) + i) ;    
        }
        cbc_namsinh.setModel(new DefaultComboBoxModel(dataNamSinh));
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbc_namsinh = new javax.swing.JComboBox<>();
        lbl_ThongBao = new javax.swing.JLabel();
        cbc_quocgia = new javax.swing.JComboBox<>();
        txt_NamBatDau = new javax.swing.JTextField();
        txt_NamketThuc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbc_namsinh.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        cbc_namsinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbc_namsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbc_namsinhActionPerformed(evt);
            }
        });

        lbl_ThongBao.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_ThongBao.setText("jLabel1");

        cbc_quocgia.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        cbc_quocgia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbc_quocgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbc_quocgiaActionPerformed(evt);
            }
        });

        txt_NamBatDau.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txt_NamBatDau.setText("1300");

        txt_NamketThuc.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txt_NamketThuc.setText("2020");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lbl_ThongBao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(605, Short.MAX_VALUE)
                        .addComponent(cbc_namsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(593, 593, 593)
                        .addComponent(txt_NamBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txt_NamketThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(cbc_quocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(581, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(lbl_ThongBao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_NamBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NamketThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(cbc_namsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(cbc_quocgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(379, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbc_namsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbc_namsinhActionPerformed
        int index = cbc_namsinh.getSelectedIndex();//Lấy ra index của vị trí combox đã chọn
        //String country = (String) cbc_quocgia.getSelectedItem();// Lấy ra giá trị của combobox đã chọn    
        lbl_ThongBao.setText(data[index]);
    }//GEN-LAST:event_cbc_namsinhActionPerformed

    private void cbc_quocgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbc_quocgiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbc_quocgiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S9_JFrameCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S9_JFrameCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S9_JFrameCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S9_JFrameCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S9_JFrameCombobox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbc_namsinh;
    private javax.swing.JComboBox<String> cbc_quocgia;
    private javax.swing.JLabel lbl_ThongBao;
    private javax.swing.JTextField txt_NamBatDau;
    private javax.swing.JTextField txt_NamketThuc;
    // End of variables declaration//GEN-END:variables
}
