/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DemoChayChu;

import static java.lang.Thread.sleep;
import java.text.Normalizer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author LegendNguyen
 */
public class Demo extends javax.swing.JFrame {

    /**
     * Creates new form Demo
     */
    public Demo() {
        initComponents();
        bl1();
       bl2();
        cong1Diem();

    }

    void cong1Diem() {//Chạy lên xuống
        String name1 = lbl_String1.getText().toString();
        char arrStringMot[] = new char[name1.length()];
        for (int i = 0; i < name1.length(); i++) {
            arrStringMot[i] = name1.charAt(i);
        }
        char arrStringHai[] = new char[name1.length()];
        for (int i = 0; i < name1.length(); i++) {
            arrStringHai[i] = '_';
        }
        Thread tr2 = new Thread() {
            int i = 0;

            @Override
            public void run() {
                while (true) {

                    char arrTemp[] = new char[name1.length()];
                    arrTemp = arrStringMot;
                    char temp = arrTemp[i];
                    arrTemp[i] = '_';
                    lbl_String2.setText(String.valueOf(arrTemp));
                    arrTemp[i] = temp;

                    char temp1 = arrStringMot[i];
                    arrStringHai[i] = temp1;
                    lbl_String1.setText(String.valueOf(arrStringHai));
                    arrStringHai[i] = '_';

                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    i++;
                    if (i == name1.length()) {
                        i = 0;
                    }
                }
            }

        };
        tr2.start();
    }

    void bl1() {//Chạy từng ký tự
        Thread tr1 = new Thread() {
            @Override
            public void run() {
                int temp = 0;
                String txt = lbl_1.getText();
                while (true) {

                    if (temp == txt.length()) {
                        temp = 0;
                    }

                    String c1 = txt.substring(temp, temp + 1);
                    String c2 = txt.substring(temp + 1, txt.length());
                    txt += c1;
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    lbl_1.setText(c2);
                    temp++;
                }
            }

        };
        tr1.start();
    }

    void bl2() {//CHạy Từng từ trong String
        Thread tr2 = new Thread() {
            int i = 0;
            String text = lbl_2.getText();

            @Override
            public void run() {
                while (true) {
                    String[] a = text.split(" ");
                    String b = a[1] + " " + a[0];
                    text = b;
                    lbl_2.setText(b);

                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    i++;
                }
            }

        };
        tr2.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_3 = new javax.swing.JLabel();
        lbl_1 = new javax.swing.JLabel();
        lbl_2 = new javax.swing.JLabel();
        lbl_String1 = new javax.swing.JLabel();
        lbl_String2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_3.setForeground(new java.awt.Color(51, 0, 255));
        lbl_3.setText("TIME");

        lbl_1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_1.setForeground(new java.awt.Color(0, 0, 153));
        lbl_1.setText("double2020");

        lbl_2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_2.setForeground(new java.awt.Color(51, 0, 255));
        lbl_2.setText("Double Java");

        lbl_String1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_String1.setForeground(new java.awt.Color(51, 0, 255));
        lbl_String1.setText("DUNGNA29@");

        lbl_String2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_String2.setForeground(new java.awt.Color(51, 0, 255));
        lbl_String2.setText("DUNGNA29@");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_1)
                    .addComponent(lbl_3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_2)
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_String2)
                            .addComponent(lbl_String1))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbl_1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_3)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbl_String1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_String2)
                        .addContainerGap(114, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Demo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JLabel lbl_String1;
    private javax.swing.JLabel lbl_String2;
    // End of variables declaration//GEN-END:variables
}
